//
// Generated by JTB 1.3.2
//

package utils;
import syntaxtree.*;
import visitor.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
@SuppressWarnings("override")
public class FirstPassVisitor extends GJDepthFirst<String,String> {
   
   int stackSpace = 0;
   int currentProcStackSpace = 0;
   boolean args = false;
   int extraSlots = 0;

   public String visit(NodeList n, String argu) {
      String ans = "";
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         ans += e.nextElement().accept(this,argu);
      }
      return ans;
   }

   public String visit(NodeListOptional n, String argu) {
      if ( n.present() ) {
         String ans = "";
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            ans += e.nextElement().accept(this,argu);
         }
         return ans;
      }
      else
         return "";
   }

   public String visit(NodeOptional n, String argu) {
      if ( n.present() )
         return n.node.accept(this,argu) + ":\n";
      else
         return "";
   }

   public String visit(NodeSequence n, String argu) {
      String ans = "";
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         ans += e.nextElement().accept(this,argu);
      }
      return ans;
   }

   public String visit(NodeToken n, String argu) { return ""; }

   /**
    * f0 -> "MAIN"
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    * f13 -> ( Procedure() )*
    * f14 -> <EOF>
    */
   public String visit(Goal n, String argu) {
      String ans = "";
      ans += "\t.text\n";
      ans += "\t.globl main\n";
      ans += "main:\n";
      ans += "\tmove $fp, $sp\n";
      ans += "\tsw $ra, -4($fp)\n";
      
      String maxArgs = n.f5.accept(this, argu);
      extraSlots = 0;
      String argsCalled = n.f8.accept(this, argu);
      if (Integer.parseInt(argsCalled) >= 5) {
         extraSlots = Integer.parseInt(argsCalled) - 4;
      }
      stackSpace = (Integer.parseInt(maxArgs) + 1 + extraSlots) * 4;
      
      ans += "\tsubu $sp, $sp, " + stackSpace + "\n";
      
      ans += n.f10.accept(this, argu);
      
      ans += "\taddu $sp, $sp, " + stackSpace + "\n";
      ans += "\tlw $ra, -4($fp)\n";
      ans += "\tj $ra\n";
      extraSlots = 0;
      ans += n.f13.accept(this, argu);
      
      ans += "\n\t.text\n";
      ans += "\t.globl _halloc\n";
      ans += "_halloc:\n";
      ans += "\tli $v0, 9\n";
      ans += "\tsyscall\n";
      ans += "\tj $ra\n\n";
      ans += "\t.text\n";
      ans += "\t.globl _print\n";
      ans += "_print:\n";
      ans += "\tli $v0, 1\n";
      ans += "\tsyscall\n";
      ans += "\tla $a0, newl\n";
      ans += "\tli $v0, 4\n";
      ans += "\tsyscall\n";
      ans += "\tj $ra\n\n";
      ans += "\t.data\n";
      ans += "\t.align 0\n";
      ans += "newl:\t.asciiz \"\\n\"\n";
      ans += "\t.data\n";
      ans += "\t.align 0\n";
      ans += "str_er:\t.asciiz \"ERROR: abnormal termination\\n\"\n";
      
      return ans;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public String visit(StmtList n, String argu) {
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> "["
    * f5 -> IntegerLiteral()
    * f6 -> "]"
    * f7 -> "["
    * f8 -> IntegerLiteral()
    * f9 -> "]"
    * f10 -> StmtList()
    * f11 -> "END"
    * f12 -> ( SpillInfo() )?
    */
   public String visit(Procedure n, String argu) {
      String ans = "";
      args = false;
      if (Integer.parseInt(n.f2.accept(this, argu)) > 4) {
         args = true;
      }
      extraSlots = 0;
      String argsCalled = n.f8.accept(this, argu);
      if (Integer.parseInt(argsCalled) >= 5) {
         extraSlots = Integer.parseInt(argsCalled) - 4;
      }
      
      String label = n.f0.accept(this, argu);
      ans += "\n\t.text\n";
      ans += "\t.globl " + label + "\n";
      ans += label + ":\n";
      ans += "\tsw $fp, -8($sp)\n";
      ans += "\tmove $fp, $sp\n";
      ans += "\tsw $ra, -4($fp)\n";
      
      String maxArgs = n.f5.accept(this, argu);
      currentProcStackSpace = (Integer.parseInt(maxArgs) + 2 + extraSlots) * 4;
      
      ans += "\tsubu $sp, $sp, " + currentProcStackSpace + "\n";
      
      ans += n.f10.accept(this, argu);
      
      ans += "\taddu $sp, $sp, " + currentProcStackSpace + "\n";
      ans += "\tlw $ra, -4($fp)\n";
      ans += "\tlw $fp, -8($sp)\n";
      ans += "\tj $ra\n";
      args = false;
      extraSlots = 0;
      return ans;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    *       | ALoadStmt()
    *       | AStoreStmt()
    *       | PassArgStmt()
    *       | CallStmt()
    */
   public String visit(Stmt n, String argu) {
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "NOOP"
    */
   public String visit(NoOpStmt n, String argu) {
      return "\tnop\n";
   }

   /**
    * f0 -> "ERROR"
    */
   public String visit(ErrorStmt n, String argu) {
      String ans = "";
      ans += "\tla $a0, str_er\n";
      ans += "\tli $v0, 4\n";
      ans += "\tsyscall\n";
      ans += "\tli $v0, 10\n";
      ans += "\tsyscall\n";
      return ans;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Reg()
    * f2 -> Label()
    */
   public String visit(CJumpStmt n, String argu) {
      String reg = n.f1.accept(this, argu);
      String label = n.f2.accept(this, argu);
      return "\tbeqz " + reg + ", " + label + "\n";
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public String visit(JumpStmt n, String argu) {
      String label = n.f1.accept(this, argu);
      return "\tb " + label + "\n";
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Reg()
    * f2 -> IntegerLiteral()
    * f3 -> Reg()
    */
   public String visit(HStoreStmt n, String argu) {
      String baseReg = n.f1.accept(this, argu);
      String offset = n.f2.accept(this, argu);
      String srcReg = n.f3.accept(this, argu);
      return "\tsw " + srcReg + ", " + offset + "(" + baseReg + ")\n";
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Reg()
    * f2 -> Reg()
    * f3 -> IntegerLiteral()
    */
   public String visit(HLoadStmt n, String argu) {
      String destReg = n.f1.accept(this, argu);
      String baseReg = n.f2.accept(this, argu);
      String offset = n.f3.accept(this, argu);
      return "\tlw " + destReg + ", " + offset + "(" + baseReg + ")\n";
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Reg()
    * f2 -> Exp()
    */
   public String visit(MoveStmt n, String argu) {
      String destReg = n.f1.accept(this, argu);
      String exp = n.f2.accept(this, "DEST:" + destReg);
      return exp;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public String visit(PrintStmt n, String argu) {
      String ans = "";
      String simpleExp = n.f1.accept(this, argu);
      
      if (simpleExp.startsWith("$")) {
         ans += "\tmove $a0, " + simpleExp + "\n";
      } else {
         ans += "\tli $a0, " + simpleExp + "\n";
      }
      ans += "\tjal _print\n";
      return ans;
   }

   /**
    * f0 -> "ALOAD"
    * f1 -> Reg()
    * f2 -> SpilledArg()
    */
   public String visit(ALoadStmt n, String argu) {
      String destReg = n.f1.accept(this, argu);
      String spilledArg = n.f2.accept(this, argu);
      int argNum = Integer.parseInt(spilledArg.replace("SPILLEDARG", ""));
      int offset = argNum * 4;
      String sourceReg = (args && argNum < 3) ? "($fp)\n" : "($sp)\n";
      return "\tlw " + destReg + ", " + offset + sourceReg;
   }

   /**
    * f0 -> "ASTORE"
    * f1 -> SpilledArg()
    * f2 -> Reg()
    */
   public String visit(AStoreStmt n, String argu) {
      String spilledArg = n.f1.accept(this, argu);
      String srcReg = n.f2.accept(this, argu);
      int argNum = Integer.parseInt(spilledArg.replace("SPILLEDARG", ""));
      int offset = argNum * 4;
      return "\tsw " + srcReg + ", " + offset + "($sp)\n";
   }

   /**
    * f0 -> "PASSARG"
    * f1 -> IntegerLiteral()
    * f2 -> Reg()
    */
   public String visit(PassArgStmt n, String argu) {
      String ans = "";
      String argNum = n.f1.accept(this, argu);
      String srcReg = n.f2.accept(this, argu);
      int argIndex = Integer.parseInt(argNum);
      
      int offset = (argIndex - 1) * 4;
      ans += "\tsw " + srcReg + ", " + offset + "($sp)\n";
      return ans;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    */
   public String visit(CallStmt n, String argu) {
      String simpleExp = n.f1.accept(this, argu);
      String ans = "";
      ans += "\tjalr " + simpleExp + "\n";
      return ans;
   }

   /**
    * f0 -> HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public String visit(Exp n, String argu) {
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public String visit(HAllocate n, String argu) {
      String ans = "";
      String size = n.f1.accept(this, "");
      String destReg = argu.replace("DEST:", "");
      
      if (size.startsWith("$")) {
         ans += "\tmove $a0, " + size + "\n";
      } else {
         ans += "\tli $a0, " + size + "\n";
      }
      
      ans += "\tjal _halloc\n";
      ans += "\tmove " + destReg + ", $v0\n";
      return ans;
   }

   /**
    * f0 -> Operator()
    * f1 -> Reg()
    * f2 -> SimpleExp()
    */
   public String visit(BinOp n, String argu) {
      String ans = "";
      String operator = n.f0.accept(this, "");
      String reg1 = n.f1.accept(this, "");
      String simpleExp = n.f2.accept(this, "");
      String destReg = argu.replace("DEST:", "");
      
      switch(operator) {
         case "PLUS" -> ans += "\tadd " + destReg + ", " + reg1 + ", " + simpleExp + "\n";
         case "MINUS" -> ans += "\tsub " + destReg + ", " + reg1 + ", " + simpleExp + "\n";
         case "TIMES" -> ans += "\tmul " + destReg + ", " + reg1 + ", " + simpleExp + "\n";
         case "DIV" -> ans += "\tdiv " + destReg + ", " + reg1 + ", " + simpleExp + "\n";
         case "LE" -> ans += "\tsle " + destReg + ", " + reg1 + ", " + simpleExp + "\n";
         case "NE" -> ans += "\tsne " + destReg + ", " + reg1 + ", " + simpleExp + "\n";
      }
      return ans;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public String visit(Operator n, String argu) {
      return n.f0.choice.toString();
   }

   /**
    * f0 -> "SPILLEDARG"
    * f1 -> IntegerLiteral()
    */
   public String visit(SpilledArg n, String argu) {
      int num = Integer.parseInt(n.f1.accept(this, argu));
      return "SPILLEDARG" + (num + ((args&&num<=3)?0:extraSlots));
   }

   /**
    * f0 -> Reg()
    *       | IntegerLiteral()
    *       | Label()
    */
   public String visit(SimpleExp n, String argu) {
      String ans = n.f0.accept(this, argu);
      if (argu.startsWith("DEST:")) {
         String destReg = argu.replace("DEST:", "");
         if(ans.startsWith("$")){
            ans = "\tmove " + destReg + ", " + ans + "\n";
         } else if(Character.isDigit(ans.charAt(0)) || ans.charAt(0) == '-') {
            ans = "\tli " + destReg + ", " + ans + "\n";
         } else {
            ans = "\tla " + destReg + ", " + ans + "\n";
         }
      }
      return ans;
   }

   /**
    * f0 -> "a0"
    *       | "a1"
    *       | "a2"
    *       | "a3"
    *       | "t0"
    *       | "t1"
    *       | "t2"
    *       | "t3"
    *       | "t4"
    *       | "t5"
    *       | "t6"
    *       | "t7"
    *       | "s0"
    *       | "s1"
    *       | "s2"
    *       | "s3"
    *       | "s4"
    *       | "s5"
    *       | "s6"
    *       | "s7"
    *       | "t8"
    *       | "t9"
    *       | "v0"
    *       | "v1"
    */
   public String visit(Reg n, String argu) {
      return "$" + n.f0.choice.toString();
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public String visit(IntegerLiteral n, String argu) {
      return n.f0.toString();
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public String visit(Label n, String argu) {
      return n.f0.toString();
   }

   /**
    * f0 -> "//"
    * f1 -> SpillStatus()
    */
   public String visit(SpillInfo n, String argu) {
      return "";
   }

   /**
    * f0 -> <SPILLED>
    *       | <NOTSPILLED>
    */
   public String visit(SpillStatus n, String argu) {
      return "";
   }
}