//
// Generated by JTB 1.3.2
//

package utils;
import syntaxtree.*;
import visitor.GJDepthFirst;

import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */

@SuppressWarnings("override")
public class FirstPassVisitor extends GJDepthFirst<BBinfo,BBinfo> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //

   public HashSet<BBinfo> allStartingBBs=new HashSet<>();
   public HashSet<BBinfo> allEndingBBs=new HashSet<>();
   public ArrayList<BBinfo> allBBs = new ArrayList<>();
   public HashMap<String, ArrayList<Integer>> labelToBB = new HashMap<>();
   public boolean isCall = false;
   public int maxParams = 0;

   public BBinfo visit(NodeList n, BBinfo argu) {
      BBinfo bb = argu;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         bb=e.nextElement().accept(this,bb);
      }
      return bb;
   }

   public BBinfo visit(NodeListOptional n, BBinfo argu) {
      if ( n.present() ) {
         BBinfo bb = argu;
         for (Enumeration<Node> e = n.elements(); e.hasMoreElements();) {
            bb=e.nextElement().accept(this, bb);
         }
         return bb;
      }
      else
         return argu;
   }

   public BBinfo visit(NodeOptional n, BBinfo argu) {
      if (n.present()){
         BBinfo bb=new BBinfo();
         allBBs.add(bb);
         argu.succ.add(bb);
         n.node.accept(this, bb);
         return bb;
      }
      else
         return argu;
   }

   public BBinfo visit(NodeSequence n, BBinfo argu) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this,argu);
      }
      return argu;
   }

   public BBinfo visit(NodeToken n, BBinfo argu) { return argu; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public BBinfo visit(Goal n, BBinfo argu) {
      BBinfo bb1 = new BBinfo();
      argu.succ.add(bb1);
      allStartingBBs.add(bb1);
      allBBs.add(bb1);
      n.f0.accept(this, argu);
      BBinfo f1info = n.f1.accept(this, bb1);
      
      BBinfo bb2 = new BBinfo();
      allBBs.add(bb2);
      allEndingBBs.add(bb2);
      if(f1info!=null)
         f1info.succ.add(bb2);

      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return bb2;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
   public BBinfo visit(StmtList n, BBinfo argu) {
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
   public BBinfo visit(Procedure n, BBinfo argu) {
      BBinfo bb = new BBinfo();
      allBBs.add(bb);
      allStartingBBs.add(bb);
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      bb.params = Integer.parseInt(n.f2.f0.toString());
      maxParams = Math.max(maxParams, bb.params);
      n.f3.accept(this, argu);
      allEndingBBs.add(n.f4.accept(this, bb));
      return bb;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public BBinfo visit(Stmt n, BBinfo argu) {
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "NOOP"
    */
   public BBinfo visit(NoOpStmt n, BBinfo argu) {
      BBinfo bb = new BBinfo();
      allBBs.add(bb);
      n.f0.accept(this, argu);
      argu.succ.add(bb);
      return bb;
   }

   /**
    * f0 -> "ERROR"
    */
   public BBinfo visit(ErrorStmt n, BBinfo argu) {
      BBinfo bb = new BBinfo();
      allBBs.add(bb);
      n.f0.accept(this, argu);
      argu.succ.add(bb);
      return bb;
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   public BBinfo visit(CJumpStmt n, BBinfo argu) {
      BBinfo bb = new BBinfo();
      argu.succ.add(bb);
      allBBs.add(bb);
      int index = allBBs.size() - 1;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      bb.use.add(n.f1.f1.f0.toString());
      n.f2.accept(this, argu);
      if (labelToBB.containsKey(n.f2.f0.toString())){
         labelToBB.get(n.f2.f0.toString()).add(index);
      } else {
         labelToBB.put(n.f2.f0.toString(), new ArrayList<>());
         labelToBB.get(n.f2.f0.toString()).add(index);
      }
      return bb;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public BBinfo visit(JumpStmt n, BBinfo argu) {
      BBinfo bb = new BBinfo();
      argu.succ.add(bb);
      allBBs.add(bb);
      int index = allBBs.size() - 1;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      if (labelToBB.containsKey(n.f1.f0.toString())){
         labelToBB.get(n.f1.f0.toString()).add(index);
      } else {
         labelToBB.put(n.f1.f0.toString(), new ArrayList<>());
         labelToBB.get(n.f1.f0.toString()).add(index);
      }
      return bb;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   public BBinfo visit(HStoreStmt n, BBinfo argu) {
      BBinfo bb = new BBinfo();
      argu.succ.add(bb);
      allBBs.add(bb);
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      bb.use.add(n.f1.f1.f0.toString());
      n.f2.accept(this, argu);
      n.f3.accept(this, argu);
      bb.use.add(n.f3.f1.f0.toString());
      return bb;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   public BBinfo visit(HLoadStmt n, BBinfo argu) {
      BBinfo bb = new BBinfo();
      argu.succ.add(bb);
      allBBs.add(bb);
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      bb.use.add(n.f1.f1.f0.toString());
      n.f2.accept(this, argu);
      bb.use.add(n.f2.f1.f0.toString());
      n.f3.accept(this, argu);
      return bb;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public BBinfo visit(MoveStmt n, BBinfo argu) {
      BBinfo bb = new BBinfo();
      argu.succ.add(bb);
      allBBs.add(bb);
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      bb.def.add(n.f1.f1.f0.toString());
      n.f2.accept(this, bb);
      return bb;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public BBinfo visit(PrintStmt n, BBinfo argu) {
      BBinfo bb = new BBinfo();
      argu.succ.add(bb);
      allBBs.add(bb);
      n.f0.accept(this, argu);
      n.f1.accept(this, bb);
      return bb;
   }

   /**
    * f0 -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public BBinfo visit(Exp n, BBinfo argu) {
      BBinfo bb = null;
      n.f0.accept(this, argu);
      return bb;
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   public BBinfo visit(StmtExp n, BBinfo argu) {
      BBinfo bb1 = new BBinfo();
      argu.succ.add(bb1);
      allBBs.add(bb1);
      n.f0.accept(this, argu);
      BBinfo f1info = n.f1.accept(this, bb1);
      BBinfo bb2 = new BBinfo();
      f1info.succ.add(bb2);
      allBBs.add(bb2);    
      n.f2.accept(this, argu);
      n.f3.accept(this, bb2);
      BBinfo bb3 = new BBinfo();
      bb2.succ.add(bb3);
      allBBs.add(bb3);     
      n.f4.accept(this, argu);
      return bb3;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   public BBinfo visit(Call n, BBinfo argu) { 
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      isCall = true;
      n.f3.accept(this, argu);
      isCall = false;
      n.f4.accept(this, argu);
      return argu;
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public BBinfo visit(HAllocate n, BBinfo argu) {
      BBinfo bb = null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      return bb;
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public BBinfo visit(BinOp n, BBinfo argu) {
      BBinfo bb = null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      argu.use.add(n.f1.f1.f0.toString());
      n.f2.accept(this, argu);
      return bb;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public BBinfo visit(Operator n, BBinfo argu) {
      BBinfo bb = null;
      n.f0.accept(this, argu);
      return bb;
   }

   /**
    * f0 -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public BBinfo visit(SimpleExp n, BBinfo argu) {
      BBinfo bb = null;
      n.f0.accept(this, argu);
      if (n.f0.choice instanceof Temp t) {
         String tempNum = t.f1.f0.tokenImage;
         argu.use.add(tempNum);
      }
      return bb;
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public BBinfo visit(Temp n, BBinfo argu) {
      BBinfo bb = null;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      if (isCall) {
         argu.use.add(n.f1.f0.toString());
         return argu;
      }
      return bb;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public BBinfo visit(IntegerLiteral n, BBinfo argu) {
      BBinfo bb = null;
      n.f0.accept(this, argu);
      return bb;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public BBinfo visit(Label n, BBinfo argu) {
      BBinfo bb = null;
      n.f0.accept(this, argu);
      if (labelToBB.containsKey(n.f0.toString())) {
         for (Integer i : labelToBB.get(n.f0.toString())) {
            allBBs.get(i).succ.add(argu);
         }
      }
      return bb;
   }
}
