//
// Generated by JTB 1.3.2
//

package utils;
import syntaxtree.*;
import visitor.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
@SuppressWarnings("override")
public class SecondPassVisitor extends GJDepthFirst<String,String> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //

   public int maxParams = 0;
   private static final String[] REGISTERS = {
      "s0","s1","s2","s3","s4","s5","s6","s7",
      "t0","t1","t2","t3","t4","t5","t6","t7","t8","t9"
   };
   public Map<AbstractMap.SimpleEntry<Integer, Integer>, AbstractMap.SimpleEntry<Boolean, Integer>> allocationMap = new HashMap<>();
   int currSpillCount = 0;
   int currParams = 0;
   int indexForMove = -1;
   boolean isMain = false;

   public String visit(NodeList n, String argu) {
      String ans="";
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         ans=ans+e.nextElement().accept(this,argu);
      }
      return ans;
   }

   public String visit(NodeListOptional n, String argu) {
      if ( n.present() ) {
         String ans="";
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            ans=ans+e.nextElement().accept(this,argu);
         }
         return ans;
      }
      else
         return "";
   }

   public String visit(NodeOptional n, String argu) {
      if ( n.present() )
         return n.node.accept(this,argu)+"\n";
      else
         return "";
   }

   public String visit(NodeSequence n, String argu) {
      String ans="";
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         ans=ans+e.nextElement().accept(this,argu);
      }
      return ans;
   }

   public String visit(NodeToken n, String argu) { return ""; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> "MAIN"
    * f1 -> StmtList()
    * f2 -> "END"
    * f3 -> ( Procedure() )*
    * f4 -> <EOF>
    */
   public String visit(Goal n, String argu) {
      String ans = "";
      isMain = true;
      currSpillCount = 0;
      currParams = 0;
      n.f0.accept(this, argu);
      ans = ans + "MAIN [0] [100] [";
      ans = ans + (maxParams+4) + "]\n";
      String f1ans = n.f1.accept(this, argu);
      ans = ans + f1ans+"\nEND\n";
      n.f2.accept(this, argu);
      currSpillCount = 0;
      currParams = 0;
      isMain = false;
      ans = ans + n.f3.accept(this, argu);
      n.f4.accept(this, argu);
      return ans;
   }

   /**
    * f0 -> ( ( Label() )? Stmt() )*
    */
    public String visit(StmtList n, String argu) {
       return n.f0.accept(this, argu);
   }
   
   /**
    * f0 -> Label()
    * f1 -> "["
    * f2 -> IntegerLiteral()
    * f3 -> "]"
    * f4 -> StmtExp()
    */
    public String visit(Procedure n, String argu) {
      String ans = "";
      currSpillCount = 0;
      ans=ans+n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      ans = ans + "[";
      ans = ans + n.f2.accept(this, argu);
      currParams = Integer.parseInt(n.f2.f0.toString());
      ans = ans + "] [100] [";
      ans = ans + (maxParams+4) + "]\n";
      n.f3.accept(this, argu);
      ans = ans + n.f4.accept(this, argu);
      currSpillCount = 0;
      currParams = 0;
      return ans;
   }

   /**
    * f0 -> NoOpStmt()
    *       | ErrorStmt()
    *       | CJumpStmt()
    *       | JumpStmt()
    *       | HStoreStmt()
    *       | HLoadStmt()
    *       | MoveStmt()
    *       | PrintStmt()
    */
   public String visit(Stmt n, String argu) {
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "NOOP"
    */
   public String visit(NoOpStmt n, String argu) {
      return "NOOP\n";
   }

   /**
    * f0 -> "ERROR"
    */
   public String visit(ErrorStmt n, String argu) {
      return "ERROR\n";
   }

   /**
    * f0 -> "CJUMP"
    * f1 -> Temp()
    * f2 -> Label()
    */
   public String visit(CJumpStmt n, String argu) {
      String ans="CJUMP ";
      n.f0.accept(this, argu);
      String f1ans = n.f1.accept(this, argu);
      String stmt1="";
      if (f1ans.startsWith("SPILLEDARG ")) {
         stmt1 = "MOVE v0 " + f1ans+"\n";
         f1ans = "v0";
      }
      ans = stmt1 + ans + f1ans + " " + n.f2.accept(this, argu)+"\n";
      return ans;
   }

   /**
    * f0 -> "JUMP"
    * f1 -> Label()
    */
   public String visit(JumpStmt n, String argu) {
      String ans="JUMP ";
      n.f0.accept(this, argu);
      ans = ans + n.f1.accept(this, argu)+"\n";
      return ans;
   }

   /**
    * f0 -> "HSTORE"
    * f1 -> Temp()
    * f2 -> IntegerLiteral()
    * f3 -> Temp()
    */
   public String visit(HStoreStmt n, String argu) {
      String ans="HSTORE";
      n.f0.accept(this, argu);
      String f1ans = n.f1.accept(this, argu);
      String f2ans = n.f2.accept(this, argu);
      String f3ans = n.f3.accept(this, argu);
      String stmt1 = "", stmt2 = "";
      if (f1ans.startsWith("SPILLEDARG ")) {
         stmt1 = "ALOAD v0 " + f1ans+"\n";
         f1ans = "v0";
      } 
      if (f3ans.startsWith("SPILLEDARG ")) {
         stmt2 = "ALOAD v1 " + f3ans+"\n";
         f3ans = "v1";
      }
      ans = stmt1 + stmt2 + ans + " " + f1ans + " " + f2ans + " " + f3ans;
      ans = "\n" + ans+"\n";
      return ans;
   }

   /**
    * f0 -> "HLOAD"
    * f1 -> Temp()
    * f2 -> Temp()
    * f3 -> IntegerLiteral()
    */
   public String visit(HLoadStmt n, String argu) {
      String ans="HLOAD";
      n.f0.accept(this, argu);
      String f1ans = n.f1.accept(this, argu);
      String f2ans = n.f2.accept(this, argu);
      String stmt1 = "", stmt2 = "";
      if (f1ans.startsWith("SPILLEDARG ")) {
         stmt1 = "ASTORE " + f1ans+" v0\n";
         f1ans = "v0";
      } 
      if (f2ans.startsWith("SPILLEDARG ")) {
         stmt2 = "ALOAD v1 " + f2ans+"\n";
         f2ans = "v1";
      }
      ans = stmt2 + ans + " " + f1ans + " " + f2ans + stmt1;
      ans = ans + " " + n.f3.accept(this, argu) + "\n";
      ans = "\n" + ans;
      return ans;
   }

   /**
    * f0 -> "MOVE"
    * f1 -> Temp()
    * f2 -> Exp()
    */
   public String visit(MoveStmt n, String argu) {
      String ans;
      n.f0.accept(this, argu);
      String f1ans = n.f1.accept(this, argu);
      indexForMove = -1;
      String f2ans = n.f2.accept(this, argu);
      if (f1ans.startsWith("SPILLEDARG ")) {
         ans = "MOVE v1 ";
         if (indexForMove!=-1) {
            ans = f2ans.substring(0, indexForMove) + ans + f2ans.substring(indexForMove);
         } else {
            if (f2ans.startsWith("SPILLEDARG ")) {
               ans = "ALOAD v0 " + f2ans + "\n" + ans + " v0\n";
            } else {
               ans = ans + f2ans;
            }
         }
         ans = ans + "\nASTORE " + f1ans + " v0\n";
      } else {
         ans = "MOVE " + f1ans + " ";
         if (indexForMove != -1) {
            ans = f2ans.substring(0, indexForMove) + ans + f2ans.substring(indexForMove);
         } else {
            if (f2ans.startsWith("SPILLEDARG ")) {
               ans = "ALOAD v0 " + f2ans + "\n" + ans + " v0\n";
            } else {
               ans = ans + f2ans;
            }
         }
      }
      ans = ans + "\n";
      return ans;
   }

   /**
    * f0 -> "PRINT"
    * f1 -> SimpleExp()
    */
   public String visit(PrintStmt n, String argu) {
      String ans="PRINT ";
      n.f0.accept(this, argu);
      String stmt1 = "";
      String f1ans = n.f1.accept(this, argu);
      if (f1ans.startsWith("SPILLEDARG ")) {
         stmt1 = "ALOAD v0 " + f1ans + "\n";
         f1ans = "v0";
      }
      ans = stmt1 + ans + f1ans + "\n";
      return ans;
   }

   /**
    * f0 -> Call()
    *       | HAllocate()
    *       | BinOp()
    *       | SimpleExp()
    */
   public String visit(Exp n, String argu) {
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "BEGIN"
    * f1 -> StmtList()
    * f2 -> "RETURN"
    * f3 -> SimpleExp()
    * f4 -> "END"
    */
   public String visit(StmtExp n, String argu) {
      String ans = "\n";
      ans = ans + saver("ASTORE",0,7,"s",0);
      ans = ans + saver("ASTORE",0,3,"a",8);
      n.f0.accept(this, argu);
      ans=ans+n.f1.accept(this, argu);
      n.f2.accept(this, argu);
      String f3ans = n.f3.accept(this, argu);
      if (f3ans.startsWith("SPILLEDARG ")) {
         ans =ans+ "\nALOAD v0" + f3ans;
      } else {
         ans = ans + "\nMOVE v0 " + f3ans;
      }
      n.f4.accept(this, argu);
      ans = ans+"\n" + saver("ALOAD",0,7,"s",0);
      ans = ans+"\n" + saver("ALOAD",0,3,"a",8);
      ans = ans + "\nEND\n";
      return ans;
   }

   /**
    * f0 -> "CALL"
    * f1 -> SimpleExp()
    * f2 -> "("
    * f3 -> ( Temp() )*
    * f4 -> ")"
    */
   public String visit(Call n, String argu) {
      StringBuilder ans = new StringBuilder();
      ans.append(saver("ASTORE", 0, 9, "t",isMain?0:8));
      ans.append(saver("ASTORE", 0, 3, "a",10+(isMain?0:8)));
      n.f0.accept(this, argu);
      String f1ans = n.f1.accept(this, argu);

      if (f1ans.startsWith("SPILLEDARG ")) {
         ans.append("ALOAD v0 ").append(f1ans).append("\n");
         f1ans = "v0";
      }

      List<String> argRegs = new ArrayList<>();
      for (Node argNode : n.f3.nodes) {
         String tempReg = argNode.accept(this, argu);
         argRegs.add(tempReg);
      }

      for (int i = 0; i < argRegs.size(); i++) {
         String arg = argRegs.get(i);
         if (arg.startsWith("SPILLEDARG ")) {
            ans.append("ALOAD v1 ").append(arg).append("\n");
            arg = "v1";
         }

         if (i < 4) {
            ans.append("MOVE a").append(i).append(" ").append(arg).append("\n");
         } else {
            ans.append("PASSARG ").append(i - 3).append(" ").append(arg).append("\n");
         }
      }
      ans.append("CALL ").append(f1ans).append("\n");
      ans.append(saver("ALOAD", 0, 9, "t",isMain?0:8));
      ans.append(saver("ALOAD", 0, 3, "a",10+(isMain?0:8)));
      indexForMove=ans.length();
      ans.append("v0");
      return ans.toString();
   }

   /**
    * f0 -> "HALLOCATE"
    * f1 -> SimpleExp()
    */
   public String visit(HAllocate n, String argu) {
      String ans="HALLOCATE";
      n.f0.accept(this, argu);
      String stmt1 = "";
      String f1ans = n.f1.accept(this, argu);
      if (f1ans.startsWith("SPILLEDARG ")) {
         stmt1 = "ALOAD v0 " + f1ans + "\n";
         f1ans = "v0";
      }
      ans = stmt1 + ans + " " + f1ans;
      indexForMove = stmt1.length();
      return ans;
   }

   /**
    * f0 -> Operator()
    * f1 -> Temp()
    * f2 -> SimpleExp()
    */
   public String visit(BinOp n, String argu) {
      String ans="";
      ans=ans+n.f0.accept(this, argu);
      String f1ans = n.f1.accept(this, argu);
      String f2ans = n.f2.accept(this, argu);
      String stmt1 = "", stmt2 = "";
      if (f1ans.startsWith("SPILLEDARG ")) {
         stmt1 = "ALOAD v0 " + f1ans+"\n";
         f1ans = "v0";
      } 
      if (f2ans.startsWith("SPILLEDARG ")) {
         stmt2 = "ALOAD v1 " + f2ans+"\n";
         f2ans = "v1";
      }
      ans = stmt1 + stmt2 + ans + " " + f1ans + " " + f2ans;
      indexForMove = stmt1.length() + stmt2.length();
      return ans;
   }

   /**
    * f0 -> "LE"
    *       | "NE"
    *       | "PLUS"
    *       | "MINUS"
    *       | "TIMES"
    *       | "DIV"
    */
   public String visit(Operator n, String argu) {
      n.f0.accept(this, argu);
      String ans = n.f0.choice.toString();
      return ans;
   }

   /**
    * f0 -> Temp()
    *       | IntegerLiteral()
    *       | Label()
    */
   public String visit(SimpleExp n, String argu) {
      return n.f0.accept(this, argu);
   }

   /**
    * f0 -> "TEMP"
    * f1 -> IntegerLiteral()
    */
   public String visit(Temp n, String argu) {
      String ans;
      n.f0.accept(this, argu);
      n.f1.accept(this, argu);
      int temp = Integer.parseInt(n.f1.f0.toString());
      if (temp < currParams) {
         return getParams(temp);
      }
      int line = n.f0.beginLine;
      // System.out.println(line+" "+temp);
      AbstractMap.SimpleEntry<Boolean, Integer> val = allocationMap.get(new AbstractMap.SimpleEntry<>(temp, line));
      if (val.getKey()) {
         if (isMain) {
            ans = "SPILLEDARG " + (val.getValue()+10);
         } else{
            ans = "SPILLEDARG " + (val.getValue() + Math.max(0, currParams - 4)+8+10);
         }
      } else {
         ans = REGISTERS[val.getValue()];
      }
      return ans;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public String visit(IntegerLiteral n, String argu) {
      n.f0.accept(this, argu);
      String ans = n.f0.toString();
      return ans;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
    public String visit(Label n, String argu) {
      n.f0.accept(this, argu);
      String ans = n.f0.toString();
      return ans;
   }

   private String getParams(int param) {
      if (param < 4) {
         return "a" + param;
      } else {
         return "SPILLEDARG " + (param - 4);
      }
   }
   
   private String saver(String type, int start, int end, String reg,int offset){
      String ans = "";
      for (int i = start; i <= end; i++) {
         if ("ASTORE".equals(type)) {
            ans = ans + "ASTORE SPILLEDARG " + (i+offset) + " " + reg + (i - start) + "\n";
         } else {
            ans = ans + "ALOAD " + reg + (i - start) + " SPILLEDARG " + (i+offset) + "\n";
         }
      }
      return ans;
   }
}
